openapi: 3.0.3
info:
  title: Narmi Public account balances alerts API
  version: v1
  description: To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
  termsOfService: https://www.narmi.com/policies/developer-terms-conditions
  contact:
    name: Narmi Support
    email: support@narmi.com
servers:
- url: https://api.sandbox.narmi.dev/
  description: ''
tags:
- name: alerts
paths:
  /v1/alerts/account/:
    get:
      operationId: account_alert_list
      description: 'List all active account alerts for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: List account alerts
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - alerts
      security:
      - oauth2:
        - read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAccountAlertRuleList'
              examples:
                AccountAlertsSampleResponse:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - - id: fe54aa39-9ea8-4078-a18c-3284530bf25a
                        alert_key: low_available_balance
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        delivery_channels:
                        - sms
                        - push
                        - email
                        threshold_amount: '200.00'
                        subscribed_accounts:
                        - ff7b4d35-7f84-493f-8f68-5ec6f28e6903
                        - 100dfef0-6a92-456e-84db-988875a48278
                        - af689bbd-36f3-4131-94c7-c2a37c7bd89d
                        last_delivered_date: '2019-08-24T14:15:22Z'
                      - id: 0a217a30-7ddd-4c91-bbcd-54d4e4a4b71d
                        alert_key: available_balance
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        delivery_channels:
                        - sms
                        - push
                        - email
                        rrule: RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE
                        subscribed_accounts:
                        - cc62d53a-8805-4381-a3b2-cd5eb30aa944
                        - 2387e2e0-8a16-44da-bfff-f09ec1993d71
                        - 61448436-c785-4790-aaf4-913b606e15bd
                        last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Account alerts sample response
          description: ''
      x-stoplight:
        id: brdiwigpt9kuv
    post:
      operationId: account_alert_create
      description: 'Activates an account alert for the user. The `alert_key` field determines which alert to activate for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Create an account alert
      tags:
      - alerts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAlertRuleRequest'
            examples:
              AccountAlertCreateResponse:
                value:
                  id: fe54aa39-9ea8-4078-a18c-3284530bf25a
                  alert_key: low_available_balance
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  delivery_channels:
                  - sms
                  - push
                  - email
                  threshold_amount: '200.00'
                  subscribed_accounts:
                  - ff7b4d35-7f84-493f-8f68-5ec6f28e6903
                  - 100dfef0-6a92-456e-84db-988875a48278
                  - af689bbd-36f3-4131-94c7-c2a37c7bd89d
                  last_delivered_date: '2019-08-24T14:15:22Z'
                summary: Account alert create response
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccountAlertRuleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AccountAlertRuleRequest'
        required: true
      security:
      - oauth2:
        - write
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAlertRule'
              examples:
                AccountAlertCreateResponse:
                  value:
                    id: fe54aa39-9ea8-4078-a18c-3284530bf25a
                    alert_key: low_available_balance
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    threshold_amount: '200.00'
                    subscribed_accounts:
                    - ff7b4d35-7f84-493f-8f68-5ec6f28e6903
                    - 100dfef0-6a92-456e-84db-988875a48278
                    - af689bbd-36f3-4131-94c7-c2a37c7bd89d
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Account alert create response
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                ValidationError:
                  value:
                    message: Invalid input.
                    id: invalid
          description: ''
      x-stoplight:
        id: mgmufjywylgmd
  /v1/alerts/account/{uuid}/:
    get:
      operationId: account_alert_retrieve
      description: 'Retrieves an account alert for the user


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Retrieve an account alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      security:
      - oauth2:
        - read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAlertRule'
              examples:
                AccountAlertSampleResponse:
                  value:
                    id: fe54aa39-9ea8-4078-a18c-3284530bf25a
                    alert_key: low_available_balance
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    threshold_amount: '200.00'
                    subscribed_accounts:
                    - ff7b4d35-7f84-493f-8f68-5ec6f28e6903
                    - 100dfef0-6a92-456e-84db-988875a48278
                    - af689bbd-36f3-4131-94c7-c2a37c7bd89d
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Account alert sample response
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
      x-stoplight:
        id: dkhydzwyhekqd
    put:
      operationId: account_alert_update
      description: 'Updates an account alert''s metadata for the user


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Update an account alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAlertRuleRequest'
            examples:
              AccountAlertUpdateResponse:
                value:
                  id: fe54aa39-9ea8-4078-a18c-3284530bf25a
                  alert_key: low_available_balance
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  delivery_channels:
                  - sms
                  - push
                  - email
                  threshold_amount: '200.00'
                  subscribed_accounts:
                  - ff7b4d35-7f84-493f-8f68-5ec6f28e6903
                  - 100dfef0-6a92-456e-84db-988875a48278
                  - af689bbd-36f3-4131-94c7-c2a37c7bd89d
                  last_delivered_date: '2019-08-24T14:15:22Z'
                summary: Account alert update response
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccountAlertRuleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AccountAlertRuleRequest'
        required: true
      security:
      - oauth2:
        - write
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAlertRule'
              examples:
                AccountAlertUpdateResponse:
                  value:
                    id: fe54aa39-9ea8-4078-a18c-3284530bf25a
                    alert_key: low_available_balance
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    threshold_amount: '200.00'
                    subscribed_accounts:
                    - ff7b4d35-7f84-493f-8f68-5ec6f28e6903
                    - 100dfef0-6a92-456e-84db-988875a48278
                    - af689bbd-36f3-4131-94c7-c2a37c7bd89d
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Account alert update response
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                ValidationError:
                  value:
                    message: Invalid input.
                    id: invalid
          description: ''
      x-stoplight:
        id: o5zaezizt5dyd
    delete:
      operationId: account_alert_delete
      description: 'Deactivates an account alert for the user. The `alert_key` field determines which alert to deactivate for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Delete an account alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      security:
      - oauth2:
        - write
      responses:
        '204':
          description: No response body
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
      x-stoplight:
        id: c2hjzsx6knfyz
  /v1/alerts/loan/:
    get:
      operationId: loan_alert_list
      description: 'List all active loan alerts for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: List loan alerts
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - alerts
      security:
      - oauth2:
        - read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLoanAlertRuleList'
              examples:
                LoanAlertsSampleResponse:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - - id: 9cedc1a9-a5e7-498c-a982-8a59b0ec2879
                        alert_key: loan_reminder
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        delivery_channels:
                        - sms
                        - push
                        - email
                        reminder_days_offset: 2
                        last_delivered_date: '2019-08-24T14:15:22Z'
                      - id: d39a3baf-b9fe-4f48-83a2-8324fa646bdc
                        alert_key: loan_overdue
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        delivery_channels:
                        - sms
                        - push
                        - email
                        last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Loan alerts sample response
          description: ''
      x-stoplight:
        id: mvexhwveu3qjr
    post:
      operationId: loan_alert_create
      description: 'Activates a loan alert for the user. The `alert_key` field determines which alert to activate for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Create a loan alert
      tags:
      - alerts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanAlertRuleRequest'
            examples:
              LoanAlertCreateResponse:
                value:
                  id: 9cedc1a9-a5e7-498c-a982-8a59b0ec2879
                  alert_key: loan_reminder
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  delivery_channels:
                  - sms
                  - push
                  - email
                  reminder_days_offset: 2
                  last_delivered_date: '2019-08-24T14:15:22Z'
                summary: Loan alert create response
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoanAlertRuleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoanAlertRuleRequest'
        required: true
      security:
      - oauth2:
        - write
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanAlertRule'
              examples:
                LoanAlertCreateResponse:
                  value:
                    id: 9cedc1a9-a5e7-498c-a982-8a59b0ec2879
                    alert_key: loan_reminder
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    reminder_days_offset: 2
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Loan alert create response
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                ValidationError:
                  value:
                    message: Invalid input.
                    id: invalid
          description: ''
      x-stoplight:
        id: b0e1kishl84bl
  /v1/alerts/loan/{uuid}/:
    get:
      operationId: loan_alert_retrieve
      description: 'Retrieves a loan alert for the user


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Retrieve a loan alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      security:
      - oauth2:
        - read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanAlertRule'
              examples:
                LoanAlertSampleResponse:
                  value:
                    id: 9cedc1a9-a5e7-498c-a982-8a59b0ec2879
                    alert_key: loan_reminder
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    reminder_days_offset: 2
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Loan alert sample response
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
      x-stoplight:
        id: gdiaffm2e2fap
    put:
      operationId: loan_alert_update
      description: 'Updates a loan alert''s metadata for the user


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Update a loan alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanAlertRuleRequest'
            examples:
              LoanAlertUpdateResponse:
                value:
                  id: 9cedc1a9-a5e7-498c-a982-8a59b0ec2879
                  alert_key: loan_reminder
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  delivery_channels:
                  - sms
                  - push
                  - email
                  reminder_days_offset: 2
                  last_delivered_date: '2019-08-24T14:15:22Z'
                summary: Loan alert update response
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoanAlertRuleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoanAlertRuleRequest'
        required: true
      security:
      - oauth2:
        - write
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanAlertRule'
              examples:
                LoanAlertUpdateResponse:
                  value:
                    id: 9cedc1a9-a5e7-498c-a982-8a59b0ec2879
                    alert_key: loan_reminder
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    reminder_days_offset: 2
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Loan alert update response
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                ValidationError:
                  value:
                    message: Invalid input.
                    id: invalid
          description: ''
      x-stoplight:
        id: tdfpt5t7ymcgs
    delete:
      operationId: loan_alert_delete
      description: 'Deactivates a loan alert for the user. The `alert_key` field determines which alert to deactivate for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Delete a loan alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      security:
      - oauth2:
        - write
      responses:
        '204':
          description: No response body
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
      x-stoplight:
        id: rgiemih3c28fg
  /v1/alerts/transaction/:
    get:
      operationId: transaction_alert_list
      description: "List all active transaction alerts for the user. \n\nAll monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.\n\n\n\n<i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>"
      summary: List transaction alerts
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - alerts
      security:
      - oauth2:
        - read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTransactionAlertRuleList'
              examples:
                TransactionAlertsSampleResponse:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - - id: 0557964c-3222-4da8-b55c-41cea97aafc4
                        alert_key: credit
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        delivery_channels:
                        - sms
                        - push
                        - email
                        transaction_query: amount>200
                        last_delivered_date: '2019-08-24T14:15:22Z'
                      - id: 75b8762d-cc66-4d18-96f4-92cb48094c73
                        alert_key: debit
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        delivery_channels:
                        - sms
                        - push
                        - email
                        transaction_query: amount>4444
                        last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Transaction alerts sample response
          description: ''
      x-stoplight:
        id: q8ea5hviogaxw
    post:
      operationId: transaction_alert_create
      description: 'Activates a transaction alert for the user. The `alert_key` determines which alert to activate for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Create a transaction alert
      tags:
      - alerts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionAlertRuleRequest'
            examples:
              CreditTransactionAlertCreateResponse:
                value:
                  id: 0557964c-3222-4da8-b55c-41cea97aafc4
                  alert_key: credit
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  delivery_channels:
                  - sms
                  - push
                  - email
                  transaction_query: amount>200
                  last_delivered_date: '2019-08-24T14:15:22Z'
                summary: Credit transaction alert create response
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransactionAlertRuleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TransactionAlertRuleRequest'
        required: true
      security:
      - oauth2:
        - write
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionAlertRule'
              examples:
                CreditTransactionAlertCreateResponse:
                  value:
                    id: 0557964c-3222-4da8-b55c-41cea97aafc4
                    alert_key: credit
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    transaction_query: amount>200
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Credit transaction alert create response
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                ValidationError:
                  value:
                    message: Invalid input.
                    id: invalid
          description: ''
      x-stoplight:
        id: 5vqiqatgwot4l
  /v1/alerts/transaction/{uuid}/:
    get:
      operationId: transaction_alert_retrieve
      description: 'Retrieves a transaction alert for the user


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Retrieve a transaction alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      security:
      - oauth2:
        - read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionAlertRule'
              examples:
                CreditTransactionAlertSampleResponse:
                  value:
                    id: 0557964c-3222-4da8-b55c-41cea97aafc4
                    alert_key: credit
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    transaction_query: amount>200
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Credit transaction alert sample response
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
      x-stoplight:
        id: knbbqep0y62ki
    put:
      operationId: transaction_alert_update
      description: 'Updates a transaction alert''s metadata for the user


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Update a transaction alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionAlertRuleRequest'
            examples:
              CreditTransactionAlertUpdateResponse:
                value:
                  id: 0557964c-3222-4da8-b55c-41cea97aafc4
                  alert_key: credit
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  delivery_channels:
                  - sms
                  - push
                  - email
                  transaction_query: amount>200
                  last_delivered_date: '2019-08-24T14:15:22Z'
                summary: Credit transaction alert update response
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransactionAlertRuleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TransactionAlertRuleRequest'
        required: true
      security:
      - oauth2:
        - write
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionAlertRule'
              examples:
                CreditTransactionAlertUpdateResponse:
                  value:
                    id: 0557964c-3222-4da8-b55c-41cea97aafc4
                    alert_key: credit
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    delivery_channels:
                    - sms
                    - push
                    - email
                    transaction_query: amount>200
                    last_delivered_date: '2019-08-24T14:15:22Z'
                  summary: Credit transaction alert update response
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                ValidationError:
                  value:
                    message: Invalid input.
                    id: invalid
          description: ''
      x-stoplight:
        id: ii5czp0iepitq
    delete:
      operationId: transaction_alert_delete
      description: 'Deactivates a transaction alert for the user. The `alert_key` determines which alert to deactivate for the user.


        All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.




        <i>How can we improve these docs?             <a href="mailto:docs+feedback@narmi.com">Share your feedback.</a></i>'
      summary: Delete a transaction alert
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          pattern: ^[0-9A-Fa-f-]{36}$
        required: true
      tags:
      - alerts
      security:
      - oauth2:
        - write
      responses:
        '204':
          description: No response body
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                NotFound:
                  value:
                    id: not_found
                    message: Not found.
          description: ''
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
              examples:
                PermissionDenied:
                  value:
                    id: permission_denied
                    message: You do not have permission to perform this action.
          description: ''
      x-stoplight:
        id: i1zlspjwfeogj
components:
  schemas:
    DeliveryChannelsEnum:
      enum:
      - sms
      - push
      - email
      type: string
      description: '* `sms` - sms

        * `push` - push

        * `email` - email'
      x-stoplight:
        id: jds3ywpdugt4t
    LoanAlertRuleRequest:
      type: object
      properties:
        alert_key:
          allOf:
          - $ref: '#/components/schemas/LoanAlertRuleAlertKeyEnum'
          description: 'Alert type, can be one of `loan_reminder` or `loan_overdue`.


            * `loan_reminder` - loan_reminder

            * `loan_overdue` - loan_overdue'
        delivery_channels:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/DeliveryChannelsEnum'
            description: 'Delivery channels, can be one of `sms`, `push`, or `email`.


              * `sms` - sms

              * `push` - push

              * `email` - email'
        reminder_days_offset:
          type: integer
          maximum: 7
          minimum: 0
          nullable: true
      required:
      - alert_key
      - delivery_channels
      x-stoplight:
        id: khappnecltn0j
    TransactionAlertRule:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        alert_key:
          allOf:
          - $ref: '#/components/schemas/AlertKey61cEnum'
          description: 'Alert type, can be one of `credit` or `debit`.


            * `credit` - credit

            * `debit` - debit'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        delivery_channels:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/DeliveryChannelsEnum'
            description: 'Delivery channels, can be one of `sms`, `push`, or `email`.


              * `sms` - sms

              * `push` - push

              * `email` - email'
        transaction_query:
          type: string
          maxLength: 256
        last_delivered_date:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - alert_key
      - delivery_channels
      - transaction_query
      x-stoplight:
        id: 4rgthd2z87x7k
    PaginatedTransactionAlertRuleList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/TransactionAlertRule'
      x-stoplight:
        id: 5dcibfdfisdew
    AccountAlertRule:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        rrule:
          type: string
          nullable: true
          description: Recurrence rule in RFC 5545 format
          maxLength: 200
        alert_key:
          allOf:
          - $ref: '#/components/schemas/AccountAlertRuleAlertKeyEnum'
          description: 'Alert type, can be one of `available_balance` or `low_available_balance`.


            * `available_balance` - available_balance

            * `low_available_balance` - low_available_balance'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        next_alert_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        threshold_amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,18}(?:\.\d{0,2})?$
          nullable: true
        delivery_channels:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/DeliveryChannelsEnum'
            description: 'Delivery channels, can be one of `sms`, `push`, or `email`.


              * `sms` - sms

              * `push` - push

              * `email` - email'
        subscribed_accounts:
          type: array
          items:
            type: string
            format: uuid
        last_delivered_date:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - alert_key
      - delivery_channels
      - subscribed_accounts
      x-stoplight:
        id: ymbfkpwtpunmq
    AlertKey61cEnum:
      enum:
      - credit
      - debit
      type: string
      description: '* `credit` - credit

        * `debit` - debit'
      x-stoplight:
        id: bwsuuwmt9dsnb
    TransactionAlertRuleRequest:
      type: object
      properties:
        alert_key:
          allOf:
          - $ref: '#/components/schemas/AlertKey61cEnum'
          description: 'Alert type, can be one of `credit` or `debit`.


            * `credit` - credit

            * `debit` - debit'
        delivery_channels:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/DeliveryChannelsEnum'
            description: 'Delivery channels, can be one of `sms`, `push`, or `email`.


              * `sms` - sms

              * `push` - push

              * `email` - email'
        transaction_query:
          type: string
          minLength: 1
          maxLength: 256
      required:
      - alert_key
      - delivery_channels
      - transaction_query
      x-stoplight:
        id: tmgfqcbyivovs
    PaginatedLoanAlertRuleList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/LoanAlertRule'
      x-stoplight:
        id: dlmnypvk45alz
    AccountAlertRuleAlertKeyEnum:
      enum:
      - available_balance
      - low_available_balance
      type: string
      description: '* `available_balance` - available_balance

        * `low_available_balance` - low_available_balance'
      x-stoplight:
        id: qthwkg8mfbejw
    LoanAlertRuleAlertKeyEnum:
      enum:
      - loan_reminder
      - loan_overdue
      type: string
      description: '* `loan_reminder` - loan_reminder

        * `loan_overdue` - loan_overdue'
      x-stoplight:
        id: qiy6mwvgwofef
    PaginatedAccountAlertRuleList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/AccountAlertRule'
      x-stoplight:
        id: lcwjdoksklfjh
    AccountAlertRuleRequest:
      type: object
      properties:
        rrule:
          type: string
          nullable: true
          description: Recurrence rule in RFC 5545 format
          maxLength: 200
        alert_key:
          allOf:
          - $ref: '#/components/schemas/AccountAlertRuleAlertKeyEnum'
          description: 'Alert type, can be one of `available_balance` or `low_available_balance`.


            * `available_balance` - available_balance

            * `low_available_balance` - low_available_balance'
        threshold_amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,18}(?:\.\d{0,2})?$
          nullable: true
        delivery_channels:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/DeliveryChannelsEnum'
            description: 'Delivery channels, can be one of `sms`, `push`, or `email`.


              * `sms` - sms

              * `push` - push

              * `email` - email'
        subscribed_accounts:
          type: array
          items:
            type: string
            format: uuid
      required:
      - alert_key
      - delivery_channels
      - subscribed_accounts
      x-stoplight:
        id: ehvxvi9lluber
    LoanAlertRule:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        alert_key:
          allOf:
          - $ref: '#/components/schemas/LoanAlertRuleAlertKeyEnum'
          description: 'Alert type, can be one of `loan_reminder` or `loan_overdue`.


            * `loan_reminder` - loan_reminder

            * `loan_overdue` - loan_overdue'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        delivery_channels:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/DeliveryChannelsEnum'
            description: 'Delivery channels, can be one of `sms`, `push`, or `email`.


              * `sms` - sms

              * `push` - push

              * `email` - email'
        last_delivered_date:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        reminder_days_offset:
          type: integer
          maximum: 7
          minimum: 0
          nullable: true
      required:
      - alert_key
      - delivery_channels
      x-stoplight:
        id: ngcjm0blyrbyi
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /v2/oauth/authorize/
          tokenUrl: /v2/oauth/token/
          scopes:
            banking:accounts:read: Can read account information.
            banking:transactions:read: Can read transaction information.
            banking:scheduled_transfers:read: Can read scheduled transfer information.
            banking:scheduled_transfers:write: Can create and update scheduled transfers.
            banking:accounts:write: Can update account information.
            banking:transactions:write: Can update transaction information.
            banking:users:read: Can read user profile information.
            banking:products:read: Can read product information.
            banking:documents:read: Can read user statements and documents.
x-stoplight:
  id: 68n444msv6n7x
